"""Bootstrap adopt and new modes — file side.

WHY THIS EXISTS
---------------
Phase 1 Spec §Bootstrap and User Stories 51-60 require a bootstrap skill that
wires any existing repo to the engine. The `adopt` mode migrates legacy ticket
statuses, replaces the repo-specific ticket skill and tests-first script with
engine-canonical versions, adds the engine config, caller workflows, ticket
template and AGENTS.md sections, and scans public files for PII to report.

The `new` mode generates the complete skeleton for a brand-new repo: AGENTS.md
with protocol sections, CONTEXT.md, a tests-first ADR, the .scratch/ layout,
CI workflow with gate checks, engine config, caller workflows, ticket template,
tests-first script, and the rendered planner instructions.

Both modes render the Cowork planner instructions from a single engine template
(``render_planner_instructions``), ensuring every repo's planner follows the
same rules: five status words, Runner/Auto-merge on every ticket, approval
tickets late in the dependency graph, roles not people, push to hand off.

This module is the pure core: it accepts all relevant file contents as input
and returns a list of file writes, diffs and PII findings. No file I/O is done
here. The ``run_adopt`` and ``run_new`` adapters read/write disk.

ADR references: ADR 0001 (tests-first, gate scripts), ADR 0002 (no real names
or IDs in public files, denylist enforcement).
"""
from __future__ import annotations

import difflib
import logging
import pathlib
import re
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Status migration
# ---------------------------------------------------------------------------

LEGACY_STATUS_MAP: dict[str, str] = {
    "complete": "done",
    "completed": "done",
    "human-task": "ready-for-developer",
}

# Matches both bold (**Status:** value) and plain (Status: value) forms.
_STATUS_LINE_RE = re.compile(
    r"^(\*\*Status:\*\*\s*|Status:\s*)(\S+)",
    re.MULTILINE | re.IGNORECASE,
)


def migrate_ticket_text(text: str) -> str:
    """Replace legacy status words with canonical ones.

    Handles both bold (**Status:** word) and plain (Status: word) forms.
    Only the status word itself is replaced; the rest of the line is unchanged.
    """
    def _replace(m: re.Match) -> str:
        prefix = m.group(1)
        word = m.group(2).strip().lower()
        canonical = LEGACY_STATUS_MAP.get(word)
        if canonical is not None:
            return prefix + canonical
        return m.group(0)

    return _STATUS_LINE_RE.sub(_replace, text)


# ---------------------------------------------------------------------------
# Canonical file contents
# ---------------------------------------------------------------------------

TICKET_SKILL_POINTER = """\
---
name: ticket
description: >-
  Implement one ticket end-to-end following the engine's runner-agnostic
  protocol. This pointer replaces any repo-specific skill.
---

# Ticket skill — engine pointer

This repo uses the engine's runner-agnostic ticket skill.
The dispatcher fetches the full skill from the engine when starting a Jules worker.

For manual reference the skill lives at:
`src/ticket_engine/resources/ticket_skill.md` in `ilegault/ticket-engine`.

Do **not** edit this file; edit the engine's skill instead so all repos stay in sync.
"""

ENGINE_CONFIG_TEMPLATE = """\
# ticket-engine configuration for this repo.
# Generated by bootstrap adopt. Customize to fit your project.
default_branch = "master"
daily_cap = 10
concurrency = 2
jules_reserve = 10
"""

TICKET_TEMPLATE = """\
# NN: <title>

**What to build:** <one-sentence description>

**Blocked by:** None

**Status:** ready-for-agent

**Runner:** any

**Auto-merge:** yes

## Acceptance criteria

- [ ]

## Comments
"""

AGENTS_MD_IMPLEMENTATION_MARKER = "<!-- ticket-engine-bootstrap: implementation-protocol -->"
AGENTS_MD_ROLES_MARKER = "<!-- ticket-engine-bootstrap: roles-not-people -->"

AGENTS_MD_IMPLEMENTATION_SECTION = f"""\
## Implementation Protocol

{AGENTS_MD_IMPLEMENTATION_MARKER}

Tickets are implemented following the engine's runner-agnostic skill.
See `src/ticket_engine/resources/ticket_skill.md` in `ilegault/ticket-engine`.

Key rules for all workers:
- Write tests from the acceptance criteria **before** any implementation.
- Cores are pure: no I/O in dispatch, integrity, or bootstrap cores.
- Every tunable lives in `.ticket-engine.toml`, never hardcoded in logic.
- Use `logging.getLogger(__name__)`; never `print()` in library code.
- One ticket, one branch, one PR. Never commit to the default branch.
"""

AGENTS_MD_ROLES_SECTION = f"""\
## Roles, Not People

{AGENTS_MD_ROLES_MARKER}

Never write real people's names, Slack IDs, or emails in code, commits,
tickets, or documentation. Refer to **roles** ("the approver", "a buyer",
"the developer"). See `ilegault/ticket-engine` ADR 0002.
"""

# ---------------------------------------------------------------------------
# Planner instructions template
# ---------------------------------------------------------------------------

PLANNER_INSTRUCTIONS_MARKER = "<!-- ticket-engine-bootstrap: planner-instructions -->"

_PLANNER_INSTRUCTIONS_TEMPLATE = """\
# Cowork Planner Instructions — {repo_name}

<!-- ticket-engine-bootstrap: planner-instructions -->

## Purpose

You are the Cowork planner for **{repo_name}**.  Your job is to translate a
user request or a product goal into a set of tickets, then hand off by pushing
those tickets into the repo's issue tracker.  You do not implement; you plan.

---

## Ticket anatomy

Every ticket you create **must** contain these fields (use the standard template):

| Field | Required value |
|---|---|
| **Status:** | One of the five words below |
| **Runner:** | A role name (never a person's name) |
| **Auto-merge:** | `yes` or `no` |
| **Blocked by:** | Ticket numbers, or `None` |

The five status words — use exactly these, no others:

- `ready-for-agent` — ready for an AI worker to pick up
- `ready-for-developer` — requires human judgement, secrets, or GitHub settings
- `in-progress` — actively being worked
- `blocked` — cannot proceed without a dependency being resolved first
- `done` — accepted and merged

---

## Writing acceptance criteria

The implementer is a cheaper agent with none of your context. A vague criterion
gets a guessed implementation and a test that proves nothing. Every ticket follows
these rules:

1. **Each criterion names its proof.** Say what a test asserts, in observable
   terms: the message text, a view's `callback_id`, the row written or its
   absence. "Then it proceeds" is not a criterion; "the reply is the Screen 2 view
   on the EPIF path, with no warning block" is.
2. **Point at the code to copy, by file and function.** Not "serialised like every
   other state (invariant 3)" but "post the card with `metadata=` the way
   `lifecycle.<function>` does, including the approver". If a ticket relies on an
   invariant, spell out what it means for this change.
3. **Check the platform before promising behaviour.** When a criterion depends on
   what an API can do (a Slack response type, a GitHub token permission), confirm
   it can, and write the criterion around what is possible.
4. **Keep tickets small: about five criteria**, or one handler or entry point.
   Split bigger work into tickets joined by `Blocked by:`.
5. **Say what tests may fake.** Name what may be faked (the Slack client, the
   network) and what must be real (the lookup or write the ticket changes, using a
   temporary copy of any file). A test that fakes the thing under change proves
   nothing.
6. **Roles, never names**, in the story as well as the fields: "the approver", "the
   requester", "a buyer" — never a real person, handle or email.

---

## Dependency ordering

Break work into the smallest independently-deliverable slices.

Place approval-required tickets (those with `Auto-merge: no` or that require a
human review gate) **as late as possible** in the dependency graph — at the
leaves of the DAG, after all automated work is complete.  This keeps the
humans-in-the-loop waiting time as short as possible and maximises the work
that can be automated without blocking.

---

## Roles, not people

Assign `Runner:` to a **role** — never a person's name, Slack handle, or email.
Roles include: `any`, `agent`, `developer`, `reviewer`, `approver`.

A role describes the capability needed, not who holds it today.  This keeps
tickets portable and avoids encoding org-chart assumptions.

---

## Handing off

Once planning is complete, push all tickets to the repo by creating GitHub
Issues (or writing them into `.scratch/phase-1/issues/`).  That push is the
handoff signal — the dispatcher will pick them up from there.

Do **not** start implementing tickets yourself.  Your output is the plan.
"""


def render_planner_instructions(repo_name: str) -> str:
    """Render the planner instructions template for a specific repo."""
    return _PLANNER_INSTRUCTIONS_TEMPLATE.replace("{repo_name}", repo_name)


def caller_dispatch_workflow(engine_version: str) -> str:
    """Caller workflow that a target repo adds to invoke the engine's reusable dispatch workflow."""
    return (
        "name: Dispatch\n"
        "\n"
        "on:\n"
        "  push:\n"
        "    branches: [master, main]\n"
        "  schedule:\n"
        "    - cron: '0 * * * *'\n"
        "  workflow_dispatch:\n"
        "\n"
        "jobs:\n"
        "  dispatch:\n"
        f"    uses: ilegault/ticket-engine/.github/workflows/dispatch.yml@{engine_version}\n"
        "    secrets:\n"
        "      PIPELINE_TOKEN: ${{ secrets.PIPELINE_TOKEN }}\n"
        "      JULES_API_KEY: ${{ secrets.JULES_API_KEY }}\n"
    )


def caller_integrity_workflow(engine_version: str) -> str:
    """Caller workflow that a target repo adds to invoke the engine's reusable integrity workflow."""
    return (
        "name: Integrity Gate\n"
        "\n"
        "on:\n"
        "  pull_request:\n"
        "    branches: [master, main]\n"
        "\n"
        "jobs:\n"
        "  integrity:\n"
        f"    uses: ilegault/ticket-engine/.github/workflows/integrity.yml@{engine_version}\n"
        "    secrets:\n"
        "      PIPELINE_TOKEN: ${{ secrets.PIPELINE_TOKEN }}\n"
    )


# ---------------------------------------------------------------------------
# New-mode skeleton templates
# ---------------------------------------------------------------------------

_CONTEXT_MD_TEMPLATE = """\
# CONTEXT — {repo_name}

## Glossary

| Term | Definition |
|---|---|
| **frontier** | The set of tickets that are `ready-for-agent` with all dependencies done |
| **claim** | A Jules session holding an in-progress ticket |
| **worker** | A Jules session assigned to implement one ticket |
| **dispatcher** | The engine workflow that starts workers and merges approved PRs |
| **verdict** | The integrity gate's decision: `pass`, `fail`, or `hold` |
| **merge hold** | A PR that passed the gate but requires human review before merge |
| **escalation** | A ticket/PR flagged for developer or stronger-model attention |
| **circuit breaker** | Auto-pause triggered when escalations exceed a threshold |
| **runner** | The role type that can execute a ticket (`agent`, `developer`, `any`) |

## Architecture overview

This repo is managed by the ticket-engine dispatcher.  See
`ilegault/ticket-engine` for the engine source.
"""

_TESTS_FIRST_ADR_TEMPLATE = """\
# ADR 0001: Tests first

**Status:** Accepted

## Context

This repo follows a tests-first discipline: tests are written from the
acceptance criteria before any implementation begins.  A test that has never
been seen to fail is not known to work.

## Decision

All implementation work must begin with a failing test.  The gate script
`scripts/check_tests_first.py` enforces this in CI.

## Consequences

- Workers are slower on the first commit but the feedback loop is tighter.
- The acceptance criteria become executable specifications.
- No `skip`, `skipif`, or `xfail` markers are allowed on tests written for this
  repo's own tickets.
"""

_CI_WORKFLOW_TEMPLATE = """\
name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -e .[dev] 2>/dev/null || pip install -e .
      - name: check_tests_first
        run: python scripts/check_tests_first.py
      - name: pytest
        run: pytest -q
"""

_SCRATCH_SPEC_PLACEHOLDER = """\
# Phase-1 Spec — {repo_name}

This file is a placeholder.  Replace it with the spec for this repo's first
phase of work.

## Sections

- Goals
- User stories
- Implementation decisions
- Testing decisions
"""

_SCRATCH_ISSUES_GITKEEP = ""


# ---------------------------------------------------------------------------
# PII scanning
# ---------------------------------------------------------------------------

_EMAIL_RE = re.compile(
    r"[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}"
)
_SLACK_ID_RE = re.compile(
    r"(?:<@)?(U[A-Z0-9]{8,10})(?:[>|]|$)"
)


@dataclass(frozen=True)
class PiiFinding:
    path: str
    line_number: int
    pattern_name: str  # "email" or "slack_id" — never the matched text


def scan_pii(public_files: dict[str, str]) -> list[PiiFinding]:
    """Scan public files for emails and Slack IDs.

    Returns PiiFinding items naming file, line number and pattern type.
    The matched text itself is never stored or returned.
    """
    findings: list[PiiFinding] = []
    for path, content in public_files.items():
        for lineno, line in enumerate(content.splitlines(), start=1):
            if _EMAIL_RE.search(line):
                findings.append(PiiFinding(path=path, line_number=lineno, pattern_name="email"))
            if _SLACK_ID_RE.search(line):
                findings.append(PiiFinding(path=path, line_number=lineno, pattern_name="slack_id"))
    return findings


# ---------------------------------------------------------------------------
# Core data structures
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class FileWrite:
    path: str
    content: str


@dataclass(frozen=True)
class FileDiff:
    path: str
    expected: str
    actual: str


@dataclass
class AdoptInput:
    engine_version: str
    ticket_files: dict[str, str]           # rel-path -> content
    skill_files: dict[str, str]            # rel-path -> content (old skill files)
    tests_first_content: str | None        # existing scripts/check_tests_first.py or None
    canonical_tests_first_content: str     # engine's canonical version
    agents_md_content: str | None          # existing AGENTS.md or None
    engine_config_content: str | None      # existing .ticket-engine.toml or None
    dispatch_workflow_content: str | None  # existing .github/workflows/dispatch.yml or None
    integrity_workflow_content: str | None
    ticket_template_content: str | None    # existing .github/ISSUE_TEMPLATE/ticket.md or None
    public_files: dict[str, str]           # rel-path -> content for PII scan
    repo_name: str = ""                    # used to render planner instructions
    planner_instructions_content: str | None = None  # existing .agents/planner/INSTRUCTIONS.md


@dataclass
class AdoptResult:
    writes: list[FileWrite] = field(default_factory=list)
    diffs: list[FileDiff] = field(default_factory=list)
    pii_findings: list[PiiFinding] = field(default_factory=list)
    unchanged: list[str] = field(default_factory=list)


@dataclass
class NewInput:
    repo_name: str
    engine_version: str
    canonical_tests_first_content: str


@dataclass
class NewResult:
    writes: list[FileWrite] = field(default_factory=list)
    unchanged: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Pure adopt core helpers
# ---------------------------------------------------------------------------

def _handle_template_file(
    path: str,
    expected: str,
    existing: str | None,
    result: AdoptResult,
) -> None:
    """Add-if-absent / diff-if-edited policy for template files."""
    if existing is None:
        result.writes.append(FileWrite(path=path, content=expected))
    elif existing == expected:
        result.unchanged.append(path)
    else:
        result.diffs.append(FileDiff(path=path, expected=expected, actual=existing))


def _handle_agents_md(
    agents_md_content: str | None,
    result: AdoptResult,
) -> None:
    """Append implementation-protocol and roles-not-people sections to AGENTS.md.

    Uses string containment to check whether canonical sections are already
    present. If both are present verbatim, the file is unchanged. If both
    markers are present but the canonical section text differs, we diff and
    report without overwriting. If markers are absent, we append the sections.
    """
    impl_section = AGENTS_MD_IMPLEMENTATION_SECTION
    roles_section = AGENTS_MD_ROLES_SECTION

    if agents_md_content is None:
        new_content = "# AGENTS.md\n\n" + impl_section + "\n" + roles_section
        result.writes.append(FileWrite(path="AGENTS.md", content=new_content))
        return

    has_impl_marker = AGENTS_MD_IMPLEMENTATION_MARKER in agents_md_content
    has_roles_marker = AGENTS_MD_ROLES_MARKER in agents_md_content

    if has_impl_marker and has_roles_marker:
        if impl_section in agents_md_content and roles_section in agents_md_content:
            result.unchanged.append("AGENTS.md")
        else:
            # Developer edited our sections; compute expected and report diff.
            # Find the start of the impl section (the ## heading before the marker).
            impl_idx = agents_md_content.find(AGENTS_MD_IMPLEMENTATION_MARKER)
            heading_pos = agents_md_content.rfind("\n## ", 0, impl_idx)
            if heading_pos != -1:
                before = agents_md_content[: heading_pos + 1]
            else:
                before = agents_md_content[: impl_idx]
            expected_md = before + impl_section + "\n" + roles_section
            result.diffs.append(FileDiff(path="AGENTS.md", expected=expected_md, actual=agents_md_content))
        return

    # One or both sections absent: append missing ones.
    new_content = agents_md_content.rstrip("\n") + "\n"
    if not has_impl_marker:
        new_content += "\n" + impl_section
    if not has_roles_marker:
        new_content += "\n" + roles_section

    result.writes.append(FileWrite(path="AGENTS.md", content=new_content))


def _handle_planner_instructions(
    repo_name: str,
    existing: str | None,
    result: AdoptResult,
) -> None:
    """Add-if-absent / diff-if-edited policy for .agents/planner/INSTRUCTIONS.md."""
    path = ".agents/planner/INSTRUCTIONS.md"
    expected = render_planner_instructions(repo_name)
    if existing is None:
        result.writes.append(FileWrite(path=path, content=expected))
    elif existing == expected:
        result.unchanged.append(path)
    else:
        result.diffs.append(FileDiff(path=path, expected=expected, actual=existing))


# ---------------------------------------------------------------------------
# Pure adopt core
# ---------------------------------------------------------------------------

def adopt(inp: AdoptInput) -> AdoptResult:
    """Pure bootstrap adopt core.

    Accepts all relevant file contents as input; returns FileWrite, FileDiff
    and PiiFinding lists. Performs no I/O.
    """
    result = AdoptResult()

    # --- Criterion 1: migrate ticket files ---
    for path, content in inp.ticket_files.items():
        migrated = migrate_ticket_text(content)
        if migrated != content:
            result.writes.append(FileWrite(path=path, content=migrated))
        else:
            result.unchanged.append(path)

    # --- Criterion 2a: replace skill files with pointer ---
    for path, content in inp.skill_files.items():
        if content == TICKET_SKILL_POINTER:
            result.unchanged.append(path)
        else:
            result.writes.append(FileWrite(path=path, content=TICKET_SKILL_POINTER))

    # --- Criterion 2b: replace tests-first script ---
    expected_tf = inp.canonical_tests_first_content
    if inp.tests_first_content is None:
        result.writes.append(FileWrite(path="scripts/check_tests_first.py", content=expected_tf))
    elif inp.tests_first_content == expected_tf:
        result.unchanged.append("scripts/check_tests_first.py")
    else:
        result.writes.append(FileWrite(path="scripts/check_tests_first.py", content=expected_tf))

    # --- Criterion 3a: engine config ---
    _handle_template_file(
        ".ticket-engine.toml",
        ENGINE_CONFIG_TEMPLATE,
        inp.engine_config_content,
        result,
    )

    # --- Criterion 3b: caller workflows ---
    _handle_template_file(
        ".github/workflows/dispatch.yml",
        caller_dispatch_workflow(inp.engine_version),
        inp.dispatch_workflow_content,
        result,
    )
    _handle_template_file(
        ".github/workflows/integrity.yml",
        caller_integrity_workflow(inp.engine_version),
        inp.integrity_workflow_content,
        result,
    )

    # --- Criterion 3c: ticket template ---
    _handle_template_file(
        ".github/ISSUE_TEMPLATE/ticket.md",
        TICKET_TEMPLATE,
        inp.ticket_template_content,
        result,
    )

    # --- Criterion 3d: AGENTS.md sections ---
    _handle_agents_md(inp.agents_md_content, result)

    # --- Criterion 3e: planner instructions ---
    if inp.repo_name:
        _handle_planner_instructions(inp.repo_name, inp.planner_instructions_content, result)

    # --- Criterion 4: PII scan ---
    result.pii_findings = scan_pii(inp.public_files)

    return result


# ---------------------------------------------------------------------------
# Adapter: read repo -> call core -> write results
# ---------------------------------------------------------------------------

def _read_optional(path: pathlib.Path) -> str | None:
    """Read a file if it exists; return None otherwise."""
    return path.read_text(encoding="utf-8") if path.is_file() else None


def _collect_ticket_files(repo_dir: pathlib.Path) -> dict[str, str]:
    files: dict[str, str] = {}
    scratch = repo_dir / ".scratch"
    if scratch.is_dir():
        for p in scratch.rglob("*.md"):
            if p.is_file() and "issues" in p.parts:
                rel = p.relative_to(repo_dir).as_posix()
                files[rel] = p.read_text(encoding="utf-8")
    return files


def _collect_skill_files(repo_dir: pathlib.Path) -> dict[str, str]:
    """Find old skill files under .agents/skills/ or .claude/skills/."""
    files: dict[str, str] = {}
    for skills_root in (repo_dir / ".agents" / "skills", repo_dir / ".claude" / "skills"):
        if skills_root.is_dir():
            for p in skills_root.rglob("SKILL.md"):
                if p.is_file():
                    rel = p.relative_to(repo_dir).as_posix()
                    files[rel] = p.read_text(encoding="utf-8")
    return files


def _collect_public_files(repo_dir: pathlib.Path) -> dict[str, str]:
    """Collect public text source files for PII scanning.

    Excludes secrets files (.env), build/dist artifacts, binaries and archives.
    Only files that could reasonably end up in a public git repo as readable
    source are scanned.
    """
    skip_dirs = {".git", ".venv", "__pycache__", "node_modules", "dist", "build"}
    skip_extensions = {
        ".pyc", ".pyo", ".so", ".dll", ".exe", ".bin",
        ".png", ".jpg", ".jpeg", ".gif", ".svg", ".ico",
        ".woff", ".ttf", ".woff2", ".eot",
        ".zip", ".pyz", ".pkg", ".pyd", ".pem", ".crt", ".key",
    }
    files: dict[str, str] = {}
    for p in repo_dir.rglob("*"):
        if not p.is_file():
            continue
        if any(part in skip_dirs for part in p.parts):
            continue
        if p.suffix in skip_extensions:
            continue
        # Skip .env files (secrets files, never public source)
        if p.name == ".env" or p.name.startswith(".env."):
            continue
        try:
            rel = p.relative_to(repo_dir).as_posix()
            content = p.read_text(encoding="utf-8", errors="ignore")
            files[rel] = content
        except OSError:
            continue
    return files


def run_adopt(
    repo_dir: pathlib.Path | str,
    engine_version: str = "v0.1.0",
    canonical_tests_first_content: str | None = None,
) -> AdoptResult:
    """Adapter: read the repo, run the adopt core, write results to disk.

    Returns the AdoptResult for callers (e.g., tests) to inspect.
    """
    repo = pathlib.Path(repo_dir)

    if canonical_tests_first_content is None:
        engine_script = (
            pathlib.Path(__file__).parent.parent.parent / "scripts" / "check_tests_first.py"
        )
        canonical_tests_first_content = (
            engine_script.read_text(encoding="utf-8") if engine_script.is_file() else ""
        )

    inp = AdoptInput(
        engine_version=engine_version,
        ticket_files=_collect_ticket_files(repo),
        skill_files=_collect_skill_files(repo),
        tests_first_content=_read_optional(repo / "scripts" / "check_tests_first.py"),
        canonical_tests_first_content=canonical_tests_first_content,
        agents_md_content=_read_optional(repo / "AGENTS.md"),
        engine_config_content=_read_optional(repo / ".ticket-engine.toml"),
        dispatch_workflow_content=_read_optional(
            repo / ".github" / "workflows" / "dispatch.yml"
        ),
        integrity_workflow_content=_read_optional(
            repo / ".github" / "workflows" / "integrity.yml"
        ),
        ticket_template_content=_read_optional(
            repo / ".github" / "ISSUE_TEMPLATE" / "ticket.md"
        ),
        public_files=_collect_public_files(repo),
        repo_name=repo.name,
        planner_instructions_content=_read_optional(
            repo / ".agents" / "planner" / "INSTRUCTIONS.md"
        ),
    )

    result = adopt(inp)

    for fw in result.writes:
        target = repo / fw.path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(fw.content, encoding="utf-8")

    for diff in result.diffs:
        logger.warning(
            "bootstrap adopt: developer-edited file not overwritten: %s\n%s",
            diff.path,
            "".join(
                difflib.unified_diff(
                    diff.expected.splitlines(keepends=True),
                    diff.actual.splitlines(keepends=True),
                    fromfile=f"{diff.path} (expected)",
                    tofile=f"{diff.path} (actual)",
                )
            ),
        )

    return result


# ---------------------------------------------------------------------------
# Pure new mode core
# ---------------------------------------------------------------------------

def new(inp: NewInput) -> NewResult:
    """Pure bootstrap new core.

    Generates the complete skeleton for a brand-new repo.  Returns FileWrite
    items for every file that should be created.  Performs no I/O.
    """
    result = NewResult()

    # AGENTS.md with protocol sections
    agents_content = (
        "# AGENTS.md\n\n"
        + AGENTS_MD_IMPLEMENTATION_SECTION
        + "\n"
        + AGENTS_MD_ROLES_SECTION
    )
    result.writes.append(FileWrite(path="AGENTS.md", content=agents_content))

    # CONTEXT.md
    context_content = _CONTEXT_MD_TEMPLATE.replace("{repo_name}", inp.repo_name)
    result.writes.append(FileWrite(path="CONTEXT.md", content=context_content))

    # Tests-first ADR
    result.writes.append(FileWrite(path="docs/adr/0001-tests-first.md", content=_TESTS_FIRST_ADR_TEMPLATE))

    # .scratch/ layout
    scratch_spec = _SCRATCH_SPEC_PLACEHOLDER.replace("{repo_name}", inp.repo_name)
    result.writes.append(FileWrite(path=".scratch/phase-1/spec.md", content=scratch_spec))
    result.writes.append(FileWrite(path=".scratch/phase-1/issues/.gitkeep", content=_SCRATCH_ISSUES_GITKEEP))

    # CI workflow
    result.writes.append(FileWrite(path=".github/workflows/ci.yml", content=_CI_WORKFLOW_TEMPLATE))

    # Engine config
    result.writes.append(FileWrite(path=".ticket-engine.toml", content=ENGINE_CONFIG_TEMPLATE))

    # Caller workflows
    result.writes.append(FileWrite(
        path=".github/workflows/dispatch.yml",
        content=caller_dispatch_workflow(inp.engine_version),
    ))
    result.writes.append(FileWrite(
        path=".github/workflows/integrity.yml",
        content=caller_integrity_workflow(inp.engine_version),
    ))

    # Ticket template
    result.writes.append(FileWrite(path=".github/ISSUE_TEMPLATE/ticket.md", content=TICKET_TEMPLATE))

    # Tests-first script
    result.writes.append(FileWrite(path="scripts/check_tests_first.py", content=inp.canonical_tests_first_content))

    # Planner instructions
    result.writes.append(FileWrite(
        path=".agents/planner/INSTRUCTIONS.md",
        content=render_planner_instructions(inp.repo_name),
    ))

    return result


# ---------------------------------------------------------------------------
# Adapter: new mode — write skeleton to disk
# ---------------------------------------------------------------------------

def run_new(
    repo_dir: pathlib.Path | str,
    repo_name: str,
    engine_version: str = "v0.1.0",
    canonical_tests_first_content: str | None = None,
) -> NewResult:
    """Adapter: call the new core and write files to disk.

    Idempotent: files that already exist with identical content are skipped
    and listed in the returned NewResult.unchanged.
    """
    repo = pathlib.Path(repo_dir)

    if canonical_tests_first_content is None:
        engine_script = (
            pathlib.Path(__file__).parent.parent.parent / "scripts" / "check_tests_first.py"
        )
        canonical_tests_first_content = (
            engine_script.read_text(encoding="utf-8") if engine_script.is_file() else ""
        )

    raw = new(NewInput(
        repo_name=repo_name,
        engine_version=engine_version,
        canonical_tests_first_content=canonical_tests_first_content,
    ))

    result = NewResult()
    for fw in raw.writes:
        target = repo / fw.path
        if target.is_file():
            existing = target.read_text(encoding="utf-8")
            if existing == fw.content:
                result.unchanged.append(fw.path)
                continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(fw.content, encoding="utf-8")
        result.writes.append(fw)

    return result


# ---------------------------------------------------------------------------
# GitHub side -- operation types (pure; no I/O, no secret values)
# ---------------------------------------------------------------------------

# The three secrets every target repo must have.  The core schedules
# SetSecretOp for any that are missing; the adapter supplies the values from
# secrets.env -- values are never handled by the core (ADR 0002).
REQUIRED_SECRETS: tuple[str, ...] = ("JULES_API_KEY", "PIPELINE_TOKEN")

# Labels created on the target repo so the dispatcher can tag PRs.
_REQUIRED_LABELS: tuple[dict, ...] = (
    {
        "name": "engine:hold",
        "color": "d93f0b",
        "description": "PR held for developer review before auto-merge",
    },
    {
        "name": "engine:escalated",
        "color": "e4e669",
        "description": "Worker escalated; needs developer or stronger-model attention",
    },
    {
        "name": "engine:windows-waiting",
        "color": "0075ca",
        "description": "Ticket waiting for a Windows worker",
    },
)

ENGINE_RULESET_NAME = "engine-branch-protection"
_INTEGRITY_CHECK_CONTEXT = "ticket-engine/integrity-gate"


@dataclass(frozen=True)
class SetSecretOp:
    name: str


@dataclass(frozen=True)
class CreateLabelOp:
    name: str
    color: str
    description: str


@dataclass(frozen=True)
class EnableAutoMergeOp:
    pass


@dataclass(frozen=True)
class EnableSecretScanningOp:
    pass


@dataclass(frozen=True)
class EnablePushProtectionOp:
    pass


@dataclass(frozen=True)
class CreateRulesetOp:
    name: str
    default_branch: str
    required_checks: tuple[str, ...]


@dataclass
class GitHubSetupInput:
    repo: str
    default_branch: str
    existing_secret_names: list[str]
    existing_label_names: list[str]
    auto_merge_enabled: bool
    secret_scanning_enabled: bool
    push_protection_enabled: bool
    existing_ruleset_names: list[str]
    python_version: str
    system_libraries: list[str]


@dataclass
class GitHubSetupResult:
    operations: list
    jules_setup_script: str
    manual_steps: list[str]


def _build_jules_setup_script(python_version: str, system_libraries: list[str]) -> str:
    nl = chr(10)
    lines = [
        "#!/usr/bin/env bash",
        "# Jules environment setup -- generated by ticket-engine bootstrap.",
        "# Paste this into the Jules session environment setup field.",
        "set -euo pipefail",
        "",
        f"# Python {python_version}",
        f"pyenv install {python_version} --skip-existing",
        f"pyenv local {python_version}",
        "",
    ]
    if system_libraries:
        lines.append("# System libraries")
        libs = " ".join(system_libraries)
        lines.append(f"apt-get install -y {libs}")
        lines.append("")
    lines.append("# Install project")
    lines.append("pip install -e .[dev] 2>/dev/null || pip install -e .")
    return nl.join(lines) + nl


def _build_manual_steps() -> list[str]:
    return [
        (
            "Verify the PIPELINE_TOKEN has the required scopes: "
            "contents:write, pull-requests:write, issues:write, actions:write."
        ),
        (
            "Confirm that GitHub Actions is enabled in the repo settings "
            "(Settings > Actions > Allow all actions)."
        ),
        (
            "After the first dispatch run, confirm the integrity gate check appears "
            "in the branch ruleset required status checks."
        ),
        (
            "Review the morning report after the first overnight run to confirm "
            "quota is within limits."
        ),
        (
            "If the repo is new, merge the first PR manually to seed the dispatch loop."
        ),
    ]


def github_setup(inp: GitHubSetupInput) -> GitHubSetupResult:
    ops: list = []

    for name in REQUIRED_SECRETS:
        if name not in inp.existing_secret_names:
            ops.append(SetSecretOp(name=name))

    if not inp.auto_merge_enabled:
        ops.append(EnableAutoMergeOp())
    if not inp.secret_scanning_enabled:
        ops.append(EnableSecretScanningOp())
    if not inp.push_protection_enabled:
        ops.append(EnablePushProtectionOp())
    if ENGINE_RULESET_NAME not in inp.existing_ruleset_names:
        ops.append(CreateRulesetOp(
            name=ENGINE_RULESET_NAME,
            default_branch=inp.default_branch,
            required_checks=(_INTEGRITY_CHECK_CONTEXT,),
        ))

    for label in _REQUIRED_LABELS:
        if label["name"] not in inp.existing_label_names:
            ops.append(CreateLabelOp(
                name=label["name"],
                color=label["color"],
                description=label["description"],
            ))

    script = _build_jules_setup_script(inp.python_version, inp.system_libraries)
    steps = _build_manual_steps()

    return GitHubSetupResult(operations=ops, jules_setup_script=script, manual_steps=steps)
