"""Bootstrap adopt mode — file side.

WHY THIS EXISTS
---------------
Phase 1 Spec §Bootstrap and User Stories 51-60 require a bootstrap skill that
wires any existing repo to the engine. The `adopt` mode migrates legacy ticket
statuses, replaces the repo-specific ticket skill and tests-first script with
engine-canonical versions, adds the engine config, caller workflows, ticket
template and AGENTS.md sections, and scans public files for PII to report.

This module is the pure core: it accepts all relevant file contents as input
and returns a list of file writes, diffs and PII findings. No file I/O is done
here. The `run_adopt` adapter reads the repo, calls this core, and writes the
results to disk.

ADR references: ADR 0001 (tests-first, gate scripts), ADR 0002 (no real names
or IDs in public files, denylist enforcement).
"""
from __future__ import annotations

import difflib
import logging
import pathlib
import re
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Status migration
# ---------------------------------------------------------------------------

LEGACY_STATUS_MAP: dict[str, str] = {
    "complete": "done",
    "completed": "done",
    "human-task": "ready-for-developer",
}

# Matches both bold (**Status:** value) and plain (Status: value) forms.
_STATUS_LINE_RE = re.compile(
    r"^(\*\*Status:\*\*\s*|Status:\s*)(\S+)",
    re.MULTILINE | re.IGNORECASE,
)


def migrate_ticket_text(text: str) -> str:
    """Replace legacy status words with canonical ones.

    Handles both bold (**Status:** word) and plain (Status: word) forms.
    Only the status word itself is replaced; the rest of the line is unchanged.
    """
    def _replace(m: re.Match) -> str:
        prefix = m.group(1)
        word = m.group(2).strip().lower()
        canonical = LEGACY_STATUS_MAP.get(word)
        if canonical is not None:
            return prefix + canonical
        return m.group(0)

    return _STATUS_LINE_RE.sub(_replace, text)


# ---------------------------------------------------------------------------
# Canonical file contents
# ---------------------------------------------------------------------------

TICKET_SKILL_POINTER = """\
---
name: ticket
description: >-
  Implement one ticket end-to-end following the engine's runner-agnostic
  protocol. This pointer replaces any repo-specific skill.
---

# Ticket skill — engine pointer

This repo uses the engine's runner-agnostic ticket skill.
The dispatcher fetches the full skill from the engine when starting a Jules worker.

For manual reference the skill lives at:
`src/ticket_engine/resources/ticket_skill.md` in `ilegault/ticket-engine`.

Do **not** edit this file; edit the engine's skill instead so all repos stay in sync.
"""

ENGINE_CONFIG_TEMPLATE = """\
# ticket-engine configuration for this repo.
# Generated by bootstrap adopt. Customize to fit your project.
default_branch = "master"
daily_cap = 10
concurrency = 2
jules_reserve = 10
"""

TICKET_TEMPLATE = """\
# NN: <title>

**What to build:** <one-sentence description>

**Blocked by:** None

**Status:** ready-for-agent

**Runner:** any

**Auto-merge:** yes

## Acceptance criteria

- [ ]

## Comments
"""

AGENTS_MD_IMPLEMENTATION_MARKER = "<!-- ticket-engine-bootstrap: implementation-protocol -->"
AGENTS_MD_ROLES_MARKER = "<!-- ticket-engine-bootstrap: roles-not-people -->"

AGENTS_MD_IMPLEMENTATION_SECTION = f"""\
## Implementation Protocol

{AGENTS_MD_IMPLEMENTATION_MARKER}

Tickets are implemented following the engine's runner-agnostic skill.
See `src/ticket_engine/resources/ticket_skill.md` in `ilegault/ticket-engine`.

Key rules for all workers:
- Write tests from the acceptance criteria **before** any implementation.
- Cores are pure: no I/O in dispatch, integrity, or bootstrap cores.
- Every tunable lives in `.ticket-engine.toml`, never hardcoded in logic.
- Use `logging.getLogger(__name__)`; never `print()` in library code.
- One ticket, one branch, one PR. Never commit to the default branch.
"""

AGENTS_MD_ROLES_SECTION = f"""\
## Roles, Not People

{AGENTS_MD_ROLES_MARKER}

Never write real people's names, Slack IDs, or emails in code, commits,
tickets, or documentation. Refer to **roles** ("the approver", "a buyer",
"the developer"). See `ilegault/ticket-engine` ADR 0002.
"""


def caller_dispatch_workflow(engine_version: str) -> str:
    """Caller workflow that a target repo adds to invoke the engine's reusable dispatch workflow."""
    return (
        "name: Dispatch\n"
        "\n"
        "on:\n"
        "  push:\n"
        "    branches: [master, main]\n"
        "  schedule:\n"
        "    - cron: '0 * * * *'\n"
        "  workflow_dispatch:\n"
        "\n"
        "jobs:\n"
        "  dispatch:\n"
        f"    uses: ilegault/ticket-engine/.github/workflows/dispatch.yml@{engine_version}\n"
        "    secrets:\n"
        "      PIPELINE_TOKEN: ${{ secrets.PIPELINE_TOKEN }}\n"
        "      JULES_API_KEY: ${{ secrets.JULES_API_KEY }}\n"
    )


def caller_integrity_workflow(engine_version: str) -> str:
    """Caller workflow that a target repo adds to invoke the engine's reusable integrity workflow."""
    return (
        "name: Integrity Gate\n"
        "\n"
        "on:\n"
        "  pull_request:\n"
        "    branches: [master, main]\n"
        "\n"
        "jobs:\n"
        "  integrity:\n"
        f"    uses: ilegault/ticket-engine/.github/workflows/integrity.yml@{engine_version}\n"
        "    secrets:\n"
        "      PIPELINE_TOKEN: ${{ secrets.PIPELINE_TOKEN }}\n"
    )


# ---------------------------------------------------------------------------
# PII scanning
# ---------------------------------------------------------------------------

_EMAIL_RE = re.compile(
    r"[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}"
)
_SLACK_ID_RE = re.compile(
    r"(?:<@)?(U[A-Z0-9]{8,10})(?:[>|]|$)"
)


@dataclass(frozen=True)
class PiiFinding:
    path: str
    line_number: int
    pattern_name: str  # "email" or "slack_id" — never the matched text


def scan_pii(public_files: dict[str, str]) -> list[PiiFinding]:
    """Scan public files for emails and Slack IDs.

    Returns PiiFinding items naming file, line number and pattern type.
    The matched text itself is never stored or returned.
    """
    findings: list[PiiFinding] = []
    for path, content in public_files.items():
        for lineno, line in enumerate(content.splitlines(), start=1):
            if _EMAIL_RE.search(line):
                findings.append(PiiFinding(path=path, line_number=lineno, pattern_name="email"))
            if _SLACK_ID_RE.search(line):
                findings.append(PiiFinding(path=path, line_number=lineno, pattern_name="slack_id"))
    return findings


# ---------------------------------------------------------------------------
# Core data structures
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class FileWrite:
    path: str
    content: str


@dataclass(frozen=True)
class FileDiff:
    path: str
    expected: str
    actual: str


@dataclass
class AdoptInput:
    engine_version: str
    ticket_files: dict[str, str]           # rel-path -> content
    skill_files: dict[str, str]            # rel-path -> content (old skill files)
    tests_first_content: str | None        # existing scripts/check_tests_first.py or None
    canonical_tests_first_content: str     # engine's canonical version
    agents_md_content: str | None          # existing AGENTS.md or None
    engine_config_content: str | None      # existing .ticket-engine.toml or None
    dispatch_workflow_content: str | None  # existing .github/workflows/dispatch.yml or None
    integrity_workflow_content: str | None
    ticket_template_content: str | None    # existing .github/ISSUE_TEMPLATE/ticket.md or None
    public_files: dict[str, str]           # rel-path -> content for PII scan


@dataclass
class AdoptResult:
    writes: list[FileWrite] = field(default_factory=list)
    diffs: list[FileDiff] = field(default_factory=list)
    pii_findings: list[PiiFinding] = field(default_factory=list)
    unchanged: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Pure adopt core helpers
# ---------------------------------------------------------------------------

def _handle_template_file(
    path: str,
    expected: str,
    existing: str | None,
    result: AdoptResult,
) -> None:
    """Add-if-absent / diff-if-edited policy for template files."""
    if existing is None:
        result.writes.append(FileWrite(path=path, content=expected))
    elif existing == expected:
        result.unchanged.append(path)
    else:
        result.diffs.append(FileDiff(path=path, expected=expected, actual=existing))


def _handle_agents_md(
    agents_md_content: str | None,
    result: AdoptResult,
) -> None:
    """Append implementation-protocol and roles-not-people sections to AGENTS.md.

    Uses string containment to check whether canonical sections are already
    present. If both are present verbatim, the file is unchanged. If both
    markers are present but the canonical section text differs, we diff and
    report without overwriting. If markers are absent, we append the sections.
    """
    impl_section = AGENTS_MD_IMPLEMENTATION_SECTION
    roles_section = AGENTS_MD_ROLES_SECTION

    if agents_md_content is None:
        new_content = "# AGENTS.md\n\n" + impl_section + "\n" + roles_section
        result.writes.append(FileWrite(path="AGENTS.md", content=new_content))
        return

    has_impl_marker = AGENTS_MD_IMPLEMENTATION_MARKER in agents_md_content
    has_roles_marker = AGENTS_MD_ROLES_MARKER in agents_md_content

    if has_impl_marker and has_roles_marker:
        if impl_section in agents_md_content and roles_section in agents_md_content:
            result.unchanged.append("AGENTS.md")
        else:
            # Developer edited our sections; compute expected and report diff.
            # Find the start of the impl section (the ## heading before the marker).
            impl_idx = agents_md_content.find(AGENTS_MD_IMPLEMENTATION_MARKER)
            heading_pos = agents_md_content.rfind("\n## ", 0, impl_idx)
            if heading_pos != -1:
                before = agents_md_content[: heading_pos + 1]
            else:
                before = agents_md_content[: impl_idx]
            expected_md = before + impl_section + "\n" + roles_section
            result.diffs.append(FileDiff(path="AGENTS.md", expected=expected_md, actual=agents_md_content))
        return

    # One or both sections absent: append missing ones.
    new_content = agents_md_content.rstrip("\n") + "\n"
    if not has_impl_marker:
        new_content += "\n" + impl_section
    if not has_roles_marker:
        new_content += "\n" + roles_section

    result.writes.append(FileWrite(path="AGENTS.md", content=new_content))


# ---------------------------------------------------------------------------
# Pure adopt core
# ---------------------------------------------------------------------------

def adopt(inp: AdoptInput) -> AdoptResult:
    """Pure bootstrap adopt core.

    Accepts all relevant file contents as input; returns FileWrite, FileDiff
    and PiiFinding lists. Performs no I/O.
    """
    result = AdoptResult()

    # --- Criterion 1: migrate ticket files ---
    for path, content in inp.ticket_files.items():
        migrated = migrate_ticket_text(content)
        if migrated != content:
            result.writes.append(FileWrite(path=path, content=migrated))
        else:
            result.unchanged.append(path)

    # --- Criterion 2a: replace skill files with pointer ---
    for path, content in inp.skill_files.items():
        if content == TICKET_SKILL_POINTER:
            result.unchanged.append(path)
        else:
            result.writes.append(FileWrite(path=path, content=TICKET_SKILL_POINTER))

    # --- Criterion 2b: replace tests-first script ---
    expected_tf = inp.canonical_tests_first_content
    if inp.tests_first_content is None:
        result.writes.append(FileWrite(path="scripts/check_tests_first.py", content=expected_tf))
    elif inp.tests_first_content == expected_tf:
        result.unchanged.append("scripts/check_tests_first.py")
    else:
        result.writes.append(FileWrite(path="scripts/check_tests_first.py", content=expected_tf))

    # --- Criterion 3a: engine config ---
    _handle_template_file(
        ".ticket-engine.toml",
        ENGINE_CONFIG_TEMPLATE,
        inp.engine_config_content,
        result,
    )

    # --- Criterion 3b: caller workflows ---
    _handle_template_file(
        ".github/workflows/dispatch.yml",
        caller_dispatch_workflow(inp.engine_version),
        inp.dispatch_workflow_content,
        result,
    )
    _handle_template_file(
        ".github/workflows/integrity.yml",
        caller_integrity_workflow(inp.engine_version),
        inp.integrity_workflow_content,
        result,
    )

    # --- Criterion 3c: ticket template ---
    _handle_template_file(
        ".github/ISSUE_TEMPLATE/ticket.md",
        TICKET_TEMPLATE,
        inp.ticket_template_content,
        result,
    )

    # --- Criterion 3d: AGENTS.md sections ---
    _handle_agents_md(inp.agents_md_content, result)

    # --- Criterion 4: PII scan ---
    result.pii_findings = scan_pii(inp.public_files)

    return result


# ---------------------------------------------------------------------------
# Adapter: read repo -> call core -> write results
# ---------------------------------------------------------------------------

def _read_optional(path: pathlib.Path) -> str | None:
    """Read a file if it exists; return None otherwise."""
    return path.read_text(encoding="utf-8") if path.is_file() else None


def _collect_ticket_files(repo_dir: pathlib.Path) -> dict[str, str]:
    files: dict[str, str] = {}
    scratch = repo_dir / ".scratch"
    if scratch.is_dir():
        for p in scratch.rglob("*.md"):
            if p.is_file() and "issues" in p.parts:
                rel = p.relative_to(repo_dir).as_posix()
                files[rel] = p.read_text(encoding="utf-8")
    return files


def _collect_skill_files(repo_dir: pathlib.Path) -> dict[str, str]:
    """Find old skill files under .agents/skills/ or .claude/skills/."""
    files: dict[str, str] = {}
    for skills_root in (repo_dir / ".agents" / "skills", repo_dir / ".claude" / "skills"):
        if skills_root.is_dir():
            for p in skills_root.rglob("SKILL.md"):
                if p.is_file():
                    rel = p.relative_to(repo_dir).as_posix()
                    files[rel] = p.read_text(encoding="utf-8")
    return files


def _collect_public_files(repo_dir: pathlib.Path) -> dict[str, str]:
    """Collect all public (non-.git) text files for PII scanning."""
    skip_dirs = {".git", ".venv", "__pycache__", "node_modules"}
    skip_extensions = {
        ".pyc", ".pyo", ".so", ".dll", ".exe", ".bin",
        ".png", ".jpg", ".jpeg", ".gif", ".svg", ".ico",
        ".woff", ".ttf", ".woff2", ".eot",
    }
    files: dict[str, str] = {}
    for p in repo_dir.rglob("*"):
        if not p.is_file():
            continue
        if any(part in skip_dirs for part in p.parts):
            continue
        if p.suffix in skip_extensions:
            continue
        try:
            rel = p.relative_to(repo_dir).as_posix()
            content = p.read_text(encoding="utf-8", errors="ignore")
            files[rel] = content
        except OSError:
            continue
    return files


def run_adopt(
    repo_dir: pathlib.Path | str,
    engine_version: str = "v0.1.0",
    canonical_tests_first_content: str | None = None,
) -> AdoptResult:
    """Adapter: read the repo, run the adopt core, write results to disk.

    Returns the AdoptResult for callers (e.g., tests) to inspect.
    """
    repo = pathlib.Path(repo_dir)

    if canonical_tests_first_content is None:
        engine_script = (
            pathlib.Path(__file__).parent.parent.parent / "scripts" / "check_tests_first.py"
        )
        canonical_tests_first_content = (
            engine_script.read_text(encoding="utf-8") if engine_script.is_file() else ""
        )

    inp = AdoptInput(
        engine_version=engine_version,
        ticket_files=_collect_ticket_files(repo),
        skill_files=_collect_skill_files(repo),
        tests_first_content=_read_optional(repo / "scripts" / "check_tests_first.py"),
        canonical_tests_first_content=canonical_tests_first_content,
        agents_md_content=_read_optional(repo / "AGENTS.md"),
        engine_config_content=_read_optional(repo / ".ticket-engine.toml"),
        dispatch_workflow_content=_read_optional(
            repo / ".github" / "workflows" / "dispatch.yml"
        ),
        integrity_workflow_content=_read_optional(
            repo / ".github" / "workflows" / "integrity.yml"
        ),
        ticket_template_content=_read_optional(
            repo / ".github" / "ISSUE_TEMPLATE" / "ticket.md"
        ),
        public_files=_collect_public_files(repo),
    )

    result = adopt(inp)

    for fw in result.writes:
        target = repo / fw.path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(fw.content, encoding="utf-8")

    for diff in result.diffs:
        logger.warning(
            "bootstrap adopt: developer-edited file not overwritten: %s\n%s",
            diff.path,
            "".join(
                difflib.unified_diff(
                    diff.expected.splitlines(keepends=True),
                    diff.actual.splitlines(keepends=True),
                    fromfile=f"{diff.path} (expected)",
                    tofile=f"{diff.path} (actual)",
                )
            ),
        )

    return result
